hwi_oauth:
    connect:
         account_connector: my.custom.user_provider
    firewall_names: [secured_area]
    fosub:
        username_iterations: 30
        properties:
           google:   google_id

    resource_owners:
        google:
            type:               google
            client_id:          196047792813-pjv0k8v7femmtf8kpji8u4d21vpen9vs.apps.googleusercontent.com
            client_secret:      v6Dn4Pon5hp0jUrFdLkMgk3i
            scope:              "email"
            options:
                display: popup
                csrf: true



