hwi_oauth:
    connect:
         account_connector: my_user_provider
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
           google:   google_id
           facebook: facebook_id

    resource_owners:
        google:
            type:               google
            client_id:          196047792813-corcpaluc70jvb5tlicpjgcuso3ei3et.apps.googleusercontent.com
            client_secret:      x0GgBFBJ9c0MGZWntNC1IGzE
            scope:              "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            options:
                display: popup
                csrf: true

        facebook:
            type:              facebook
            client_id:         329299620966358
            client_secret:     93339391b04e1e72bad9575749815787
            scope:            ""
